### ISSUE TITLE
Devel: Ansible-your git version is too old to fully support the depth argument

### ISSUE THREAD

**Issue by akniffe1** [rocknsm/rock#101]
after attempting to upgrade an existing ROCK2.0 host I received this error:
````
TASK [Checkout ROCK Bro scripts] ***********************************************
fatal: [simplerockbuild.simplerock.lan]: FAILED! => {"before": "dae039b7c6e526128c9b36647e0663b8e65c66b5", "changed": false, "failed": true, "msg": "Local modifications exist in repository (force=no).", "warnings": ["Your git version is too old to fully support the depth argument. Falling back to full checkouts."]}
	to retry, use: --limit @/root/rock/ansible/rock.retry
````
This shouldn't stop the execution of the task, as the dependency limitation is just allowing a fallback to a full checkout. 

@bndabbs suggested that the real cause of the problem is permissions on the /opt/bro/share/bro/site/scripts/ directory, and to get past the immediate problem running:
````
chown -R bro /opt/bro/share/bro/site/scripts/
````

Additionally, rock.yml could probably avert this issue with the addition of the following task after "Symlink offline ROCK bro scripts"

````
- name: Update owner for ROCK NSM Bro scripts
  file:
    path: /opt/bro/share/bro/site/scripts/rock
    owner: "{{ bro_user }}"
    group: "{{ bro_group }}"
    state: directory
    recurse: yes
    follow: yes
  ````

**Comment by dcode** [comment]
The git version isn't the problem here, that's just the warning text. The actual error is:
```
Local modifications exist in repository (force=no).
```

When performing an online install, ROCK defaults to using the linked upstream git repository. The error suggests that you made some changes to that git repository, and just like git will tell you were you to do a manual pull, your changes would be overwritten.

There are...3 options here:

1. We keep the behavior as it is, preserving this safety net of your changes.
2. We tell it to force update, potentially losing your changes (saves bandwidth over # 3)
3. We use the offline approach of pulling down the tarball snapshot and unpacking it. This would blindly overwrite your changes and risks clunky update mechanisms (we'd have to track the commit serial number to check for latest).

Please validate my assumptions above about the root cause are correct. If not we'll have to dig deeper about a bug. My suspicion is that this is the desired, but undocumented behavior.

**Comment by akniffe1** [comment]
I think you're absolutely correct about the root cause. I found that by uninstalling / reinstalling the bro* packages (completely removing / rebuilding /opt/bro/ ) I didn't have this problem, which certainly supports your theory. Additionally, starting / stopping and rerunning the deployment didn't replicate the problem. I'd say for now lets stick with 1, close the issue, and let this suffice for basic documentation on the behavior.

**Comment by dcode** [comment]
Did you make any modifications to the rock scripts?

**Comment by akniffe1** [comment]
Not on this issue, I did all the above steps manually.

**Comment by dcode** [comment]
Can this be closed?

**Comment by akniffe1** [comment]
Closing thanks for the help.
