### ISSUE TITLE
ROCK 2.0 and broctl meltdown

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#136]
@dcode @jeffgeiger @akniffe1 @peasead @bndabbs @kazimer

_Ok gang, I am looking for some feedback on these comments - please be gentle ;)_ 

## Situation
A ROCK 2.0 sensor will have Bro effectively disabled or "nuked" if specifically, the command `sudo broctl` is ran.  

### The bottom-line is:
1. It is reasonable for a ROCK 2.0 admin to tune Bro on the ROCK 2.0 sensor.     
2. IDS'es must be tuned to their environment to be effective, and to environment changes.  Fundamentally, this means they must be periodically reloaded+restarted in a timely manner, normally.  The alternative is to run something simple like full packet capture or something that does not require tuning.       
3. It is reasonable and expected for the ROCK 2.x sensor to be highly stable -- I dare say "resilient" to interruptions of forensic data acquisition, even during a rolling tuning session.  I personally expect a ROCK sensor to be equal or better in this regard to the Security Onion project sensor platform. 

### Use Cases

1. **Use case 1** - Performing incident response - quickly build a ROCK sensor and start collecting at a SPAN port; incident responder realizes some additional scripts need to be enabled and inadvertently "nukes" the sensor - now faced with figuring out how to quickly bring the sensor back up, or rebuild; time is of the essence in this scenario. Responder would need to quickly pivot to something else for network forensic data.  
2. **Use case 2** - Admin is performing routine maintenance on a infrastructure ROCK 2.0 sensor, inadvertently "nukes" the sensor by using the `sudo` command.  If this is the only sensor, then the visibility gap, at least from Bro will quickly grow quite big.  Admin would need to start analyzing full packet capture if Stenographer is not enabled, or enable Stenographer as a stop-gap.  
3. **Use case 3** - ROCK 2.0 sensor is put in place for an emergency insider-threat investigation.  Inadvertently running sudo "nuke's" the sensor.  This could become a serious incident if critical data was missed. 

### ACLs
Could there be a better fix for the unexpected disabling of the ROCK 2.0 sensor by unknowingly running `#sudo broctl`?  SELinux could be a fix, but there may be a simpler one:  ACL's:  

[RHEL Storage Admin Guide - ACLs](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Storage_Administration_Guide/ch24.html#target-setup-configure-acl)

[Configuring ACLs with RHEL 7](http://www.tecmint.com/rhcsa-exam-configure-acls-and-mount-nfs-samba-shares/)

### SELinux
Utilize both ACLs and SELinux Role-Based Access Control/Multi-Level Security/Category Security configurations.  

### Scripts
Additionally, I believe that with Bro 2.5 in its current stats of unusual behavior when interacting with it as an administrator, that abstracting the native commands with scripts could be an alternative, or complimentary effort.  This may end up being the simplest way to fix this issue, though less "pure." 

I place the blame on Vern and his Deutschland minions for this lovely situation!;)

**Comment by dcode** [comment]
First, thanks for the "issue". As I've mentioned in some previous issues, it's really most helpful if you can provide specific details or log entries that help us reproduce and troubleshoot the problem.

That said I put in a fair amount of effort trying to solve this, and I'm not done. First, the ACLs thing doesn't apply because when you run a blanket sudo, you elevate to root. Root has a special privilege called [Discretionary Access Control Override](https://www.reddit.com/r/linux/comments/1cnn15/for_chmod_why_is_root_allowed_to_execute_programs/) which basically says "I'm root, I do what I want". This leaves us two options to ensure admins don't wreck themselves:

1. Remove the DAC Override capability from root
2. Fence out root using SELinux

Neither of these would be an expected "feature" of ROCK and would just lead to more confusion.

The best we can do is better documentation encouraging users to use:
```
sudo -u bro broctl
```
or
```
systemctl restart broctl
```
In our offline discussion, we talked about some recovery scripts that could be used to get out of a jam. That's another thing we can implement, supplemented with better docs.

As a final note, I would add that we're not trying to compete with Security Onion. We're both trying to carve out a slice of need to save the world. Our goal is a minimalist, secure (with SELinux) Linux distribution as a baseline to collect data for response operations. There's certainly places we can learn from @dougburks work but at the end of the day, I see ROCK as a different kind of thing.

**Comment by dougburks** [comment]
Hello all,

Since I was tagged by @dcode, I'll offer a quick comment.  We faced similar issues with broctl in Security Onion and ended up creating /usr/sbin/broctl which runs the real broctl the way we want/need it to be run:
https://github.com/Security-Onion-Solutions/security-onion/issues/1043

I'm not sure if this would help you guys or not, but I thought I'd mention it in the spirit of cooperation.

**Comment by dcode** [comment]
Thanks @dougburks! I considered something like that, but wasn't sure if users would manually run `/opt/bro/bin/broctl` anyhow. It seems like a useful handrail anyhow to guide users to _Do The Right Thing_:tm:.

**Comment by dougburks** [comment]
Anecdotally, I don't think I've seen any reports of Bro permissions issues since we added /usr/sbin/broctl.  I think we can _almost always_ count on users being lazy and just typing `sudo broctl`.  :smirk:

**Comment by charlesfair** [comment]
Great to see you around these parts Doug!  Thanks for the insight about your approach to broctl.  

I am completely onboard with NOT running Broctl with root permissions.  I guess u didn't realize our earlier design left that gap.  I really any to leverage SELinux as much as possible on this sensor platform.  

I've got some ideas about rapid integration of existing Securityonion sensors with a ROCK flyaway kit. If I actually get some time I might be able to cook something up.  So, basically a solid ad-hoc data acquisition "broker" of sorts.  You know, it's important to capture all the things!

**Comment by charlesfair** [comment]
@dcode 

COA 00: Run no "operational" commands as UID 0, but a different user that has only limited rights - for instance user "rockop" could only sudo and run with the rights of "rockadmin" - a limited elevated privilege user.  For true UID 0 rights, a third account would be needed.  

[Check out the CIS Baseline for CentOS 7](https://benchmarks.cisecurity.org/downloads/show-single/?file=centos7.100)

**Comment by charlesfair** [comment]
@dcode 

COA 00: Run no "operational" commands as UID 0, but a different user that has only limited rights - for instance user "rockop" could only sudo and run with the rights of "rockadmin" - a limited elevated privilege user.  For true UID 0 rights, a third account would be needed.  

[Check out the CIS Baseline for CentOS 7](https://benchmarks.cisecurity.org/downloads/show-single/?file=centos7.100)

**Comment by dcode** [comment]
I'll come back to this, but please use the issue tracker for issues and feature requests. This is not a chat. Please contact us on Slack to have discussions.
