### ISSUE TITLE
The Stenographer Service Calls /bin/true Instead of Starting Stenographer 

### ISSUE THREAD

**Issue by Dioberne** [rocknsm/rock#168]
/etc/systemd/system/stenographer.service 

Aka

https://github.com/rocknsm/rock/blob/3326f4bdf2789703f8e152ee117f0037d3476a51/playbooks/files/stenographer.service

has /bin/true subbed in instead of actually starting Stenographer. Right now the README assumes the service is fully functional. The ideal solution would be that the service would be fully functional. The documentation should at least show a working way to get stenographer set up.

**Comment by dcode** [comment]
@Dioberne this falls into the category of "needs more documentation". Since stenographer doesn't support listening on multiple interfaces we run multiple instances of it. In order to accomplish this we use "systemd template files". For instance, try running:

```
$ sudo systemctl list-units | grep stenographer
  stenographer.service                                                                      loaded active exited    packet capture to disk
  stenographer@enp0s31f6.service                                                            loaded active running   packet capture to disk
```

You'll see I have a `stenographer@enp0s31f6.service`. This uses the template to start the stenographer service for that template. The `stenographer.service` file is a placeholder that will actually control the other interfaces in the event you start, stop, or restart. The one case where this doesn't automatically propagate is enabling/disabling the service. The easiest way to achieve this is to set `enable_stenographer: true` in `/etc/rocknsm/config.yml` and then re-run the deploy script.

However, if you've deviated from the default setup too much, this could overwrite some of your changes. In that case, you can always just run `sudo systemctl enable stenographer@interface_name` where `interface_name` is the name of your interface. This happens in the deploy script [here](https://github.com/rocknsm/rock/blob/master/playbooks/deploy-rock.yml#L792-L798). Note that you'll have to create the `/etc/stenographer/config.interface_name` file...again with your interface name.

**Comment by Dioberne** [comment]
@dcode thanks for the information. That is very helpful.
