### ISSUE TITLE
We need to add DAG enabled Suricata to Rock

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#216]
We need to add support for the DAG to Suricata in Rock. Current working code to do this is:

[026_sensor_suricata-install.sh.txt](https://github.com/rocknsm/rock/files/1555258/026_sensor_suricata-install.sh.txt)

**Comment by dcode** [comment]
As long as we're doing this, might as well implement #219 as well.

**Comment by dcode** [comment]
Same discussion applies as to the Bro DAG support (see #217). Suricata doesn't use a plugin approach to capture methods, so the only way to do this is to create a "suricata-dag" package and ensure it declares conflict and providing equivalency to the "suricata" package. 

Also, since Endace libraries are closed source, we cannot build them on the [RockNSM COPR](https://copr.fedorainfracloud.org/coprs/g/rocknsm/rocknsm-2.1/) like we build the rest of the packages.

**Comment by dcode** [comment]
This is no longer needed.
