### ISSUE TITLE
We need to add DAG support to Bro

### ISSUE THREAD

**Issue by grantcurell** [rocknsm/rock#217]
The only thing that is necessary for this to work is that Bro knows where the DAG-enabled libpcap is from https://github.com/rocknsm/rock/issues/215.

Current code for doing this:
[027_sensor_bro-install.sh.txt](https://github.com/rocknsm/rock/files/1555264/027_sensor_bro-install.sh.txt)

**Comment by dcode** [comment]
This is probably a bit more than beginner. The _right_ way to do this is to implement a Bro plugin for DAG. I don't think it's super hard, but knowledge of C++ would be required. For an interim capability, a `bro-dag` package could be created.

We build our Bro packages on the Fedora COPR. [Here](http://copr-dist-git.fedorainfracloud.org/cgit/@rocknsm/rocknsm-2.1/bro.git/tree/bro.spec?h=epel7) is our existing Bro spec file. You can modify that spec file with the required compilation options, rename the package, and mark it as "Conflicts: bro" and "Provides: bro".

Also, since Endace support libraries are closed source, we cannot build the RPMs there. They will have to be built offline and uploaded to our repo.

**Comment by dcode** [comment]
This is no longer needed.
