### ISSUE TITLE
Snort Shared Object Rules

### ISSUE THREAD

**Issue by charlesfair** [rocknsm/rock#28]
Heads-up.  Checked out the Snort setup for SimpleRock with a friend and it looks like the new build with Snort has a misconfiguration with Share Object Rules in snort.conf and pulledpork.  

http://blog.talosintel.com/2009/01/using-vrt-certified-shared-object-rules.html 

More info on Shared Object rules:  

> http://blog.snort.org/2011/02/snort-shared-object-rules.html 
> However, some may be finding it difficult to use the rules, so let me point you to a couple guides.  One guide is here, on Snort.org, at the bottom of the "platform" list.  The VRT also has a blog post that can help you install the Shared Object rules.
> 
> But, by far, the easiest way to use Shared Object rules reliably is through the configuration and use of a tool called PulledPork, which JJ Cummings of Sourcefire is the primary author of.  After the configuration of PulledPork, the tool will generate the Shared Object rule stubs for you, and place everything in the correct directories for ease of use.  This is amongst the many features of PulledPork (including flowbit dependency resolving) which are useful.

**Comment by dcode** [comment]
When we initially set this up, I couldn't get pulled pork to generate these rules on a recent operating system. The pre-built libs that are distributed stop at like EL5 (I don't remember exactly the OS, it was a while back though... like 2011). 

I'm not opposed to get this working, but it's a lower priorty for us since we tend to focus on Bro and follow on capabilities at this point.

If you have the expertise and can work out the process and document the steps, we can work it in sooner.

**Comment by charlesfair** [comment]
No prob, will work on it and talk to some of the Snort people around here to get it working.

**Comment by pabit** [comment]
Are you plan to add Suricata support?

**Comment by charlesfair** [comment]
pabit, the answer is YES!  (sorry about the long-delayed follow-up)

**Comment by dcode** [comment]
This is not a priority for ROCK 2.x since we use Suricata by default. If someone wants to modify the pulled-pork setup to handle this, then a pull request will be welcomed. Until then, closing this issue.
