### ISSUE TITLE
Docket and Stenographer should reference localhost

### ISSUE THREAD

**Issue by jokvedaras** [rocknsm/rock#464]
I ran into some problems setting up docket and stenographer since the "ansible_default_ipv4.address" within "steno_host" in roles/docket/defaults/main.yml and "host" in roles/stenographer/templates/stenographer-config.j2 did not get set to 127.0.0.1.  When it was set to the actual IP of the host, Docket failed to communicate w/ Stenographer.

**Comment by jokvedaras** [comment]
I have the code to fix, just need to know if it should actually be 127.0.01

**Comment by dcode** [comment]
So, in general for an all in one system, we've put everything that wasn't user facing on loop back. We move it to the site IP (to borrow from elastic's terminology) for services that needed it to communicate. Whatever IP Stenographer binds to, must be the IP that the certificate is generated for (as IPAltName) and Docket must be configured to use (because the client validates the server by IP or DNS in TLS)
