### ISSUE TITLE
Elastic Stack 7.6 SIEM app Detections non-functional without extensive additional configuration

### ISSUE THREAD

**Issue by pullthru** [rocknsm/rock#540]
The SIEM app Detections functionality will not work with a default installation of RockNSM 2.5.0 with the rocknsm-2.5.0-2002.iso.  

The SIEM app at first appears to be non-functional with basic authentication and require a commercial license for AD/LDAP authentication.  I do have a guide on how to get it working with Basic Authentication that a community user created.  The level and amount of configuration necessary will likely cause frustration for new users.  

I can update this issue with the guide when I get back to my system.

**Comment by webhead404** [comment]
I am working on this as well, and the SIEM app itself works fine without the detections for me. I have documented the changes required to get detections working however the Basic Auth issue is still a problem. I am wondering if this could be alleviated by creating a Kibana user with the same credentials as the Basic Auth user for ROCK. This may not be best practice but for single node it seems like an approach.

**Comment by peasead** [comment]
You have to enable TLS between Elasticsearch and Kibana.

I've done this, there's nothing of note generated by Zeek or Suricata data in the Detection Engine at this time.

The ROCK dashboards and visualizations are much better.

**Comment by tompoper23** [comment]
Gents, can I either get the guide or can this be re-opened? With Elastic 7.8 released, the detection piece has been upgraded. Also, its the only thing that kicked rocknsm for my org when we were looking for a new NSM.

**Comment by dcode** [comment]
We want to make this easier in the future, but in the meantime, you need to configure TLS between Kibana and Elasticsearch. In order to use the detection engine (and several other features in Kibana), Kibana generates API keys for each backend job. It refuses to do this without encryption between Kibana and Elasticsearch.

Elastic has the steps necessary to do this [here](https://www.elastic.co/guide/en/kibana/current/configuring-tls.html#configuring-tls-kib-es). Note, you do not need to configure TLS between Elasticsearch nodes (i.e. on port 9300/TCP).

Again, in the future, I hope this is more turn key.

**Comment by tompoper23** [comment]
Dcode, thanks for the quick reply.

**Comment by tompoper23** [comment]
Derrick,

Thanks for the info. Maybe put this info in the rock wiki? Me and my guys
have been following the steps on the elastic site trying to set up the
x-pack security for a while now. I am the only one that hasn't given up
yet. I think this is the only step we didnt do because it wasnt prescribed
be elastic as required.

I'll try it with a fresh install today. Where in the install scripts would
this configuration be added iot make this a natural state for rock?

Sincerely, Tom

**Comment by webhead404** [comment]
@tompoper23 as @dcode described this isn't turn key. It will more than likely have to be an option going forward because if it was done by default it would break a lot of configuration. I have done this and here is a reference for you: https://gist.github.com/webhead404/c2a95cff6061ab53cfd0bf8dd8c1558e

It is a little out of date but for the most part it is correct. Are you in the ROCK Slack?

**Comment by peasead** [comment]
@tompoper23 we wrote a guide for another entity that is using the SIEM and ROCK on how to do encryption on a single and multi-node deployment. Once we get some breathing room with our day jobs, we'll sanitize and convert it over.

**Comment by tompoper23** [comment]
I am not. I should jump in.

**Comment by webhead404** [comment]
Either that or join the Rock Community: https://community.rocknsm.io/

**Comment by tompoper23** [comment]
> @tompoper23 as @dcode described this isn't turn key. It will more than likely have to be an option going forward because if it was done by default it would break a lot of configuration. I have done this: https://gist.github.com/webhead404/c2a95cff6061ab53cfd0bf8dd8c1558e
> 
> It is a little out of date but for the most part it is correct. I strongly advise you to separate your ROCK sensor from Elastic because it will make this configuration easier.
> 
> Are you in the ROCK Slack? What is a good way to reach you?

webhead404 I cannot find the slack channel. Is there an invite or can someone drop a link? Id like to be able to chat with you guys outside of this git repo.

**Comment by webhead404** [comment]
@tompoper23 found it for you. https://tiny.cc/rockslack

**Comment by peasead** [comment]
This isn't a complete solution, but it's very close. Tuning needed for Docket.

https://huntops.blue/2020/08/02/securing-rocknsm.html

**Comment by tompoper23** [comment]
@peasead The guide is spot on, however, I think the stack is no longer gathering data from the sensor. I stood up a new stack, latest version. Followed the guide to the letter. I have data for a short time, then the net traffic stops. Any clues as why it would?

**Comment by peasead** [comment]
Just to follow up, this was a tabbing issue in Logstash. You figured it out and data is flowing.

**Comment by tompoper23** [comment]
The only thing I changed was the tabbing. The first filter in the logstash
output has tabs and then 3 spaces to align it where it ends up after
install. I cleared the 3 spaces, then tabbed each of the output lines just
past the curly brace at the start of the block. Restarted logstash and data
for the entire day showed up instantly in kibana.

Tom
